src/app/app-routing.module.ts, src/app/app.component.html, src/app/game/game.component.html
Sets up basic routing to all components that need them, as well as default route to the game component. Moved the sketchpad to the game component and out of the app-component.html
=> Base routes

angular.json, server.js
changes build path to just dist and also sets up the basic backend pieces to start with.
=> basic backend scaffold

server.js, server/config/socket.conf.js
setup barebones socket-io backend to flesh out on the front end and update as needed
=> basic starting framework for backend sockets

server.js, server/config/socket.conf.js, src/app/app.module.ts, src/app/game/game.component.html
=> Socket io work

src/app/chat/chat.component.ts, src/app/services/sketch.service.ts
Made changes to the services components to add chat and draw sockets
Co-authored-by: KyleOC1983 <kyle.t.oconnor@gmail.com>
=> Added chat and draw sockets to front end

src/app/app.component.html, src/app/app.component.scss, src/app/app.module.ts, src/app/chat/chat.component.scss, src/app/game/game.component.html, src/app/game/game.component.scss, src/app/scoreboard/scoreboard.component.html, src/app/scoreboard/scoreboard.component.scss, src/app/scoreboard/scoreboard.component.spec.ts, src/app/scoreboard/scoreboard.component.ts, src/app/sketchpad/sketchpad.component.scss
Adds leaderboard and win boxes, acct + login / logout icons, leave game btn
=> Scoreboard

src/app/app-routing.module.ts, src/app/interfaces/player.interface.ts, src/app/services/game.service.spec.ts, src/app/services/game.service.ts
Inital game service setup.
Initial player interface
=> initial game service commit + player interface

src/app/game/game.component.html, src/app/game/game.component.scss, src/app/game/game.component.ts
prompts user for display name before being able to view game.
=> Dialog box

src/app/home/home.component.html, src/app/home/home.component.scss
removed duplicate login button and also removed create account since it is no longer needed.
=> Home update

src/app/app-routing.module.ts, src/app/app.component.html, src/app/app.component.ts, src/app/app.module.ts, src/app/login/login.component.html, src/app/login/login.component.ts, src/app/services/authentication.service.spec.ts, src/app/services/authentication.service.ts, src/environments/environment.prod.ts, src/environments/environment.ts
Created the authentication login button on the app.component.html with a logout.  Also, I have implemented auth guard for all routes.
=> Authentication and Auth Guard created

src/app/game/game.component.html, src/app/game/game.component.scss
prompts user to enter a display name before game component appears.
=> Prompt for DispalyName in Game Component

src/app/home/home.component.html, src/app/home/home.component.scss
styles home component to match other components
=> Home component

src/app/app.component.html
adds mat-button property to btns, makes acct icon only visible after login
=> adds mat-button to btns, acct icon after login

src/app/home/home.component.html, src/app/home/home.component.ts
Added snackbar so a user that isn't signed in gets a pop up letting them know they need to sign in to create a new game.
=> AddedSnackBartoCreateGame

src/app/creategame/creategame.component.html, src/app/creategame/creategame.component.scss
removed scroll bars on side of create game component.
=> removedScrollArrows

src/app/creategame/creategame.component.html, src/app/creategame/creategame.component.scss
adding some spacing to the create game page.
=> movedRoundsdisplaydown

src/styles.scss
=> centeredSnackBarText

src/app/app-routing.module.ts, src/app/creategame/creategame.component.ts, src/app/guards/join-game.guard.spec.ts, src/app/guards/join-game.guard.ts, src/app/home/home.component.html, src/app/home/home.component.ts, src/app/services/game.service.ts
Join game guard added
Routing to a game by id working
Set default values for score and rounds
=> Join Game guard and functions added.

server/config/socket.conf.js, src/app/game/game.component.ts, src/app/services/game.service.ts, src/app/services/socket.service.ts, src/app/sketchpad/sketchpad.component.ts
Adds code for sockets and firebase integration, most of the functions still need to be built out but they should be pointing in the right direction at least
=> Sockets for future firebase integration

src/app/game/game.component.html, src/app/game/game.component.ts, src/app/services/game.service.ts
added topic functions to game component and game service
=> addedTopicFunctions

src/app/game/game.component.html, src/app/scoreboard/scoreboard.component.html
Moved a button and added a routerlink to another.
=> MovedTopicButtonAddedLinktoLeaveGame

src/app/game/game.component.ts
fixes some errors that popped up in a merge to master
=> fixes a couple of errors

server/config/socket.conf.js, src/app/game/game.component.html, src/app/game/game.component.ts, src/app/home/home.component.html, src/app/home/home.component.ts, src/app/services/game.service.ts, src/app/services/socket.service.ts
chat adds usernames correctly now, moved functionality to socket service off of game service
=> makes a bunch of fixes, moved stuff to sockets

src/app/game/game.component.html
Added keyup.enter to display name
=> AddedKeyuptoDisplayName

src/app/chat/chat.component.html, src/app/chat/chat.component.ts, src/app/services/host.store.service.spec.ts, src/app/services/host.store.service.ts, src/app/services/socket.service.ts
=> More sockets and stuff

src/app/services/game.service.ts
added a function to remove games older than 2 hours from creation once the user clicks on to create a new game.
=> Removing of old games

src/app/chat/chat.component.ts, src/app/services/game.service.ts
Pulling topic from firestore and comparing the topic with chat to see if players guess right.
=> getTopicFromFS

server/config/socket.conf.js, src/app/creategame/creategame.component.ts, src/app/game/game.component.html, src/app/game/game.component.ts, src/app/interfaces/gameInfo.interface.ts, src/app/services/game.service.ts, src/app/services/socket.service.ts
Display game info.
Host status observable working.
Add host to game on creation.
GameInfo interface
=> Host status update

src/app/game/game.component.html, src/app/game/game.component.ts, src/app/scoreboard/scoreboard.component.html, src/app/scoreboard/scoreboard.component.ts
All players (users and artist) populate to scoreboard.
Binds variables from game component.
=> Users to scoreboard

src/app/game/game.component.html, src/app/game/game.component.ts
Only the artist can see the topic display.
=> hidesTopicFromNonArtists

src/app/chat/chat.component.scss, src/app/chat/chat.component.ts
cleans up chat code, blocks chat output box from growing with text
=> cleans up chat component

src/app/chat/chat.component.scss, src/app/chat/chat.component.ts
=> Chat cleanup

src/app/game/game.component.html, src/app/game/game.component.ts
super clean code that fixes subscribe in game comp
=> Hidefromnon artist

src/app/chat/chat.component.ts
=> fixes chat for real this time

src/app/chat/chat.component.ts
This one actually fixes the chat, I really promise this time
=> wraps entire chat function in valid If statement

server/config/socket.conf.js, src/app/chat/chat.component.ts, src/app/game/game.component.ts, src/app/scoreboard/scoreboard.component.ts, src/app/services/game.service.ts, src/app/services/socket.service.ts, src/app/sketchpad/sketchpad.component.ts
Updates chat win function - assigns points, clears the topic and round
updates scoreboard with new scores.
=> Win point function

src/app/chat/chat.component.html, src/app/chat/chat.component.ts
disables chat for the current artist
=> disables chat for currentArtist

src/app/sketchpad/sketchpad.component.html, src/app/sketchpad/sketchpad.component.ts
sets up so only artist can draw and see the clear draw button
=> Sketchpad artist only

src/app/game/game.component.html
creates a display of the current round out of the max rounds set
=> displays currentRound / maxRounds

src/app/game/game.component.html, src/app/game/game.component.ts, src/app/services/game.service.ts, src/app/services/socket.service.ts
Leave game works correctly for all users.
moves game play buttons into single div in game component.
=> Leave game retry

src/app/game/game.component.html
=> fixDisplayIssuewithTopic

server/config/socket.conf.js, src/app/services/socket.service.ts
Round increments when host becomes artist again (all players in the room have had a turn as artist)
gameEnd socket fires when player score = max score OR when max rounds has been reached.
gameEnd socket still needs fleshed out functionality
=> Adds round counter and game end functions

server/config/socket.conf.js, src/app/game/game.component.html, src/app/game/game.component.ts, src/app/services/socket.service.ts
initial setup for timer.  Sockets and Observable created.  Everyone can see the timer counting down.
=> Fun with timers

src/app/game/game.component.ts
Timer no longer resets when clicking new topic once a topic has been initiated.
=> TimerNoLongerRestarts

package-lock.json, package.json, src/app/app.module.ts, src/app/scoreboard/scoreboard.component.html
Sorts scoreboard by high score
=> SortsScoreboard

src/app/chat/chat.component.ts
Added line of code to add .includes to message string that allows for an answer anywhere in the message box to work
=> fixed message bug to include

server/config/socket.conf.js, src/app/chat/chat.component.ts, src/app/services/socket.service.ts
System sends a message at the end of a turn letting users know who the new Artist is.
=> Clear board message

server/config/socket.conf.js, src/app/chat/chat.component.html, src/app/chat/chat.component.ts, src/app/services/socket.service.ts
Game end shows winner and disables new topic.
=> Game end cleanup

src/app/chat/chat.component.scss, src/app/game/game.component.html, src/app/game/game.component.scss, src/app/scoreboard/scoreboard.component.scss
Looks better on screens of 885px or less.
=> @mediaWork

src/app/scoreboard/scoreboard.component.scss
removes underline from leaderboard
=> removes leaderboard underline

src/app/chat/chat.component.ts
=> fixes win messages
